name: Env

description: Initialize benchmark environment with Node.js and Rust

runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Activate corepack
      shell: bash
      run: corepack enable
    - name: Install dependencies with pnpm
      shell: bash
      run: pnpm install
