name: Env

description: Initialize benchmark environment with Node.js and Rust

runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Activate corepack
      shell: bash
      run: |
        # corepack > 0.24.1 will use native fetch
        # and native fetch not support HTTP_PROXY
        # https://github.com/nodejs/undici/issues/1650
        npm install -g corepack@0.24.1
        corepack enable
    - name: Install dependencies with pnpm
      shell: bash
      run: pnpm install --prefer-frozen-lockfile --prefer-offline
    - name: Set Rspack Dir
      shell: bash
      run: |
        if [[ ! -z "$PNPM_CACHE" ]]; then
          echo "RSPACK_DIR=$PNPM_CACHE/rspack" >> $GITHUB_ENV
        fi
