name: Env

description: Initialize benchmark environment with Node.js and Rust

runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Activate corepack
      shell: bash
      run: corepack enable
    - name: Get pnpm cache directory path
      id: pnpm-cache-dir-path
      shell: bash
      run: echo "dir=$(pnpm store path)" >> $GITHUB_OUTPUT
    - uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-
    - name: Install dependencies with pnpm
      shell: bash
      run: pnpm install
    - name: Cache Rust toolchain and dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
