name: Env

description: Initialize benchmark environment with Node.js and Rust

runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: 22
    - name: Activate corepack
      shell: bash
      run: |
        npm install -g corepack@latest
        echo "Corepack version: $(corepack --version)"
        corepack enable
    - name: Install dependencies with pnpm
      shell: bash
      run: pnpm install --prefer-frozen-lockfile --prefer-offline
    - name: Set Rspack Dir
      shell: bash
      run: |
        if [[ ! -z "$PNPM_CACHE" ]]; then
          echo "RSPACK_DIR=$PNPM_CACHE/rspack" >> $GITHUB_ENV
        fi
