name: "Prepare Rspack Binding"
description: "Checkout, build, and upload rspack native bindings"

inputs:
  repository:
    description: "The rspack repository to use"
    required: true
    default: "web-infra-dev/rspack"
  path:
    description: "Destination path to clone"
    required: true
    default: ".rspack"
  ref:
    description: "The branch, tag or SHA to checkout"
    required: true
    default: "main"
  node-version:
    description: "The version of Node.js to set up"
    required: true
    default: "18"

outputs:
  artifact-name:
    description: "The name of the uploaded artifact"

runs:
  using: composite
  steps:
    - name: Build Rspack
      shell: bash
      run: >-
        node bin/cli.js build
        --repository ${{ inputs.repository }}
        --ref ${{ inputs.ref }}
        --binding true
        --js false
    - uses: actions/upload-artifact@v4
      with:
        name: binding-linux-x64-gnu
        path: ${{ inputs.path }}/crates/node_binding/*.node
        compression-level: 9
    - shell: bash
      run: echo "artifact-name=binding-linux-x64-gnu" >> $GITHUB_OUTPUT
