name: "Check if the latest commit is on the main branch"
description: "Checks if the current commit is the latest commit on the main branch."

inputs:
  path:
    description: "Destination path to the repository"
    required: true

outputs:
  result:
    description: "Boolean indicating if the current commit is the latest commit on the main branch."

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        git fetch origin/main
        LATEST_COMMIT=$(git rev-parse origin/main)
        CURRENT_COMMIT=$(git rev-parse HEAD)
        if [ "$LATEST_COMMIT" = "$CURRENT_COMMIT" ]; then
          echo "result=true" >> $GITHUB_OUTPUT
        else
          echo "result=false" >> $GITHUB_OUTPUT
        fi
      working-directory: ${{ inputs.path }}
